package PoliticsDB::Site::Model::DBIC;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'PoliticsDB::Schema',
    
    connect_info => {
        dsn      => PoliticsDB::Config->get('db')->{dsn},
        user     => PoliticsDB::Config->get('db')->{user},
        password => PoliticsDB::Config->get('db')->{password},
    }
);

=head1 NAME

PoliticsDB::Site::Model::DBIC - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<PoliticsDB::Site>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<PoliticsDB::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.62

=head1 AUTHOR

Shantanu Bhadoria

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
